version: '3'
services:
  mysql-cscs:
    image: mysql:5.7
    container_name: mysql-cscs
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql    
  myapp-demo:
    image: myapp-demo
    container_name: myapp-demo
    ports:
      - "5001:8081"
    depends_on:
      - mysql-cscs
    environment:
      - DATABASE_HOST=mysql-cscs
      - DATABASE_USER=app_user
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306      